algoritmo "exer1"
// Função :    converter real em dolar
// Autor :  Vinícius de Paiva Mendonça Silva
// Data : 03/05/2022
// Seção de Declarações 
var
dolar,reais,cotacao: real

inicio
// ENTRADA

escreval("escreva o valor do dolar: ")
leia(dolar)
escreval("escreva o valor do real que deseja ser convertido: ")
leia(reais)



// PROCESSAMENTO

cotacao <- (reais/dolar)

//Saida
escreval("O valor total da sua cotação é :", cotacao)


fimalgoritmo
