algoritmo "atividade6"
// Função : atividade numero 5
// Autor : Vinícius de Paiva
// Data : 29/03/2022
var
nome: caractere

n1,n2,n3,n4, media :real



inicio
escreval("--Vmaos calcular a media do aluno--")
escreval("----------------------------------------------")
escreval("Nome do aluno: ")
leia(nome)
escreval("----------------------------------------------")
escreval("digite o valor da primeira nota do aluno: ")
leia(n1)
escreval("----------------------------------------------")
escreval("digite o valor da segunda nota do aluno: ")
leia(n2)
escreval("----------------------------------------------")
escreval("digite o valor da terceira nota do aluno: ")
leia(n3)
escreval("----------------------------------------------")
escreval("digite o valor da quarta nota do aluno: ")
leia(n4)
escreval("----------------------------------------------")

//procesamento

media <- (n1+n2+n3+n4) /4

limpatela

//saida

escreval("----------------------------------------------")
escreval("A media do aluno é:", media)
escreval("----------------------------------------------")

fimalgoritmo


