Algoritmo "areaquadrado"
// este algoritimo solicita o lado = calcula e area do quadrado

Var
lado,area: real


Inicio
// entrada
escreval("--------------------------")
escreval("Digite um lado do quadrado")
escreval("--------------------------")
leia(lado)
escreval("--------------------------")

// procesamento
area <- lado^2

// saida
escreval ("A área do quadrado é:", area)

Fimalgoritmo