Algoritmo "impargrande"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Professor   : Cintia pinho
// Descrição   : escreva na tela impares entre 100 a 200
// Autor(a)    : Vinícius de Paiva
// Data atual  : 06/09/2022
Var
i: inteiro

Inicio
escreval("-----------------IMAPRES ENTRE 100 A 200-------------------")

para i de 100 ate 200 faca
   se(i%2 = 1)entao
    escreval(i)
   fimse
fimpara

Fimalgoritmo