Algoritmo "soma_infini"
// Professor   : Cintia Pinho
// Descrição   : some quanto for neseario para o usuario
// Autor(a)    : Vinícius de Piava Mendonça Silva
// Data atual  : 11/09/2022

Var
acu,num: inteiro


Inicio
escreval("-------------------PARA ENCERRAR, DIGITE 0---------------------")
repita
escreval("Digite um número")
leia(num)
acu <- acu+num
escreval("SOMANDO...", acu)
ate (num=0)
interrompa



Fimalgoritmo