Algoritmo "codigosimples_26_07"
// Descrição   : codigosimples - verificar se o numero e par ou impar
// Autor(a)    : Vinícius de Piava Mendonça Silva
// Data atual  : 26/07/2022
Var
numero: inteiro

Inicio
escreval("Digite um numero desejar")
leia(numero)

// processamento
 Se (numero mod 2=0) entao
   escreval("Seu numero e par")
  senao
   escreval("Seu numero e impar")
 fimse
Fimalgoritmo
